bururung/src/main/java/com/hifive/bururung/global/common/JwtAuthenticationEntryPoint.java, bururung/src/main/java/com/hifive/bururung/global/common/JwtAuthenticationFilter.java, bururung/src/main/java/com/hifive/bururung/global/common/TokenProvider.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/ControllerAdvice.java, bururung/src/main/java/com/hifive/bururung/global/exception/CustomException.java, bururung/src/main/java/com/hifive/bururung/global/exception/ErrorResponse.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/ErrorCode.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/MemberErrorCode.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/exception -> develop
ControllerAdvice를 통한 전역 예외 처리 구현. CustomException, ErrorCode 이용.
=> 전역 예외 처리 구현

bururung/build.gradle, bururung/src/main/java/com/hifive/bururung/domain/email/controller/EmailController.java, bururung/src/main/java/com/hifive/bururung/domain/email/dto/EmailAuthConstants.java, bururung/src/main/java/com/hifive/bururung/domain/email/dto/EmailCheckRequest.java, bururung/src/main/java/com/hifive/bururung/domain/email/dto/EmailSendRequest.java, bururung/src/main/java/com/hifive/bururung/domain/email/dto/EmailType.java, bururung/src/main/java/com/hifive/bururung/domain/email/service/EmailService.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/UserDetailsServiceImpl.java, bururung/src/main/java/com/hifive/bururung/global/config/AsyncConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/MailConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/MemberErrorCode.java, bururung/src/main/resources/application.yml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/email -> develop
회원가입, 비밀번호 변경 시 필요한 인증 메일 발송,인증 기능 추가.
메일 발송은 비동기로 처리함.
=> 인증 메일 발송, 인증 기능 추가

bururung/src/main/java/com/hifive/bururung/TestController.java, bururung/src/main/java/com/hifive/bururung/domain/member/controller/MemberController.java, bururung/src/main/java/com/hifive/bururung/domain/member/dto/ChangePasswordRequest.java, bururung/src/main/java/com/hifive/bururung/domain/member/dto/FindEmailRequest.java, bururung/src/main/java/com/hifive/bururung/domain/member/entity/Member.java, bururung/src/main/java/com/hifive/bururung/domain/member/repository/MemberRepository.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/IMemberService.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/MemberService.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/UserDetailsServiceImpl.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/member/findid-resetpassword -> develop
=> 아이디 찾기, 비밀번호 변경 기능

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/entity/TaxiShare.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/entity/TaxiShareJoin.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareService.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/TaxiShareErrorCode.java, bururung/src/main/resources/mapper/taxi/TaxiShareMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
ex) feat/taxi/create -> dev
택시 공유 게시물 생성 관련 로직  추가
=> Feat: TaxiShare Create 기능 구현

bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
ex) bugfix/cors -> develop
=> Fix: cors 에러 수정

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/dto/LatLng.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareJoinRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareService.java, bururung/src/main/java/com/hifive/bururung/global/common/NearbyLocationFinder.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/TaxiShareJoinErrorCode.java, bururung/src/main/resources/mapper/taxi/TaxiShareJoinMapper.xml, bururung/src/main/resources/mapper/taxi/TaxiShareMapper.xml
-[v] 기능 추가
ex) feat/taxi/crerate -> dev
택시공유 참여 관련 기능 구현
- 참여 insert
- 방 참여자 수 cnt
- 예외 추가
- 출발지 근처 걸어갈 수 있는 거리 계산 클래스 추가
- 출발지 근처 리스트 뽑기 로직
=> Feat:택시공유 참여 관련 기능 구현

bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/controller/ServiceRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/CarInformationResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/DriverInformationResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/DrivingInformation.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/repository/ServiceRegistrationRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/IServiceRegistrationService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/ServiceRegistrationService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare-participant/details -> develop
- 운전자 정보 조회
- 차량 정보 조회
- 백엔드 & DB 연결 1 : 운전자 정보 출력
- 백엔드 & DB 연결 2 : 차량 정보 출력
=> Feat: 차량 공유 상세 정보 조회

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/dto/TaxiShareJoinRequest.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/dto/TaxiShareResponse.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareJoinRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareService.java, bururung/src/main/resources/mapper/taxi/TaxiShareJoinMapper.xml, bururung/src/main/resources/mapper/taxi/TaxiShareMapper.xml
-[v] 기능 추가
-[v] 기능 수정
ex) feat/taxi/create-> dev
- 택시 공유 리스트 로직 수정
- 택시 공유 신청 기능 추가
- 예외처리 추가
=> Feat: 택시 공유 리스트 로직 수정, 신청 기능 추가, 예외처리 추가

bururung/build.gradle, bururung/src/main/java/com/hifive/bururung/domain/member/controller/MypageController.java, bururung/src/main/java/com/hifive/bururung/domain/member/entity/Member.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/IMypageService.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/MypageService.java, bururung/src/main/java/com/hifive/bururung/global/common/s3/FileSubPath.java, bururung/src/main/java/com/hifive/bururung/global/common/s3/S3Uploader.java, bururung/src/main/java/com/hifive/bururung/global/common/s3/UploadFileDTO.java, bururung/src/main/java/com/hifive/bururung/global/config/S3Config.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/FileErrorCode.java, bururung/src/main/resources/application.yml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[v] 의존성, 환경 변수, 빌드 관련 코드 업데이트
feature/member/file-upload -> develop
S3 설정 추가
S3 파일 업로드, 파일 삭제 구현
마이페이지 프로필 이미지 업로드 구현
=> S3 파일 업로드, 파일 삭제, 마이페이지 프로필 업로드

bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarRegistrationController.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
fFeature/car share/check-verified-member -> develop
- 차량 등록 인증 여부 체크 메소드 추가
- 차량 조회 시 인증된 사용자에게는 범죄 기록 파일을 반환하지 않는다. (수정 금지)
- 인증이 되지 않은 사용자는 프론트 UI를 재전송 버튼으로 활성화를 시키기 위해 백 로직 구현
=> Feat : 차량 등록 인증 여부 체크 메서드 구현

bururung/src/main/java/com/hifive/bururung/domain/statistics/controller/StatisticsController.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/dto/AgeGroupRatioResponse.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/dto/GenderRatioResponse.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/dto/MemberNameWithRateResponse.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/dto/MonthlyNewMemberResponse.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/repository/IStatisticsMapper.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/service/IStatisticsService.java, bururung/src/main/java/com/hifive/bururung/domain/statistics/service/StatisticsService.java, bururung/src/main/resources/mapper/statistics/StatisticsMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/statistics/member-rate -> develop
- 남여 비율 조회 기능 추가
- 연령대별 회원 수 조회 기능 추가
- 매 달 신규 가입 수 조회 기능 추가
- 회원 별점 순으로 조회 기능 추가
- 4가지 기능 모두 성공
=> Feat: 통계 데이터 조회 기능 추가

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareJoinRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareService.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/TaxiShareErrorCode.java, bururung/src/main/resources/mapper/taxi/TaxiShareJoinMapper.xml, bururung/src/main/resources/mapper/taxi/TaxiShareMapper.xml
-[] 기능 추가
feat/taxi/create -> develop
- 택시 공유 삭제 기능 추가
- 예외 에러코드 추가
=> Feat: 택시 공유 삭제 기능 추가, 예외 에러코드 추가

bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/reservation > develop
- 차량 상세 조회 추가 구현
- 차량 공유 예약 기능 구현
- 차량 상세 조회 시 운전자 정보, 차량 정보, 차량 운행 정보 조회 가능
=> Feat: 차량 상세 조회 및 예약 기능 구현

bururung/build.gradle, bururung/src/main/java/com/hifive/bururung/domain/notification/controller/NotificationController.java, bururung/src/main/java/com/hifive/bururung/domain/notification/dto/NotificationDTO.java, bururung/src/main/java/com/hifive/bururung/domain/notification/dto/NotificationListResponse.java, bururung/src/main/java/com/hifive/bururung/domain/notification/entity/Notification.java, bururung/src/main/java/com/hifive/bururung/domain/notification/repository/INotificationMapper.java, bururung/src/main/java/com/hifive/bururung/domain/notification/repository/INotificationRepository.java, bururung/src/main/java/com/hifive/bururung/domain/notification/service/INotificationService.java, bururung/src/main/java/com/hifive/bururung/domain/notification/service/NotificationService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebSocketConfig.java, bururung/src/main/resources/mapper/notification/NotificationMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
-[v] 의존성, 환경 변수, 빌드 관련 코드 업데이트
feature/notifications -> develop
- 읽은 알림, 읽지 않은 알림, 발신자로 조회한 알림 조회 기능 추가
- 알림 보내기 기능 추가
- 알림 읽기 기능 추가
- 알림 삭제 기능 추가
- 웹소켓 설정 파일 추가
- 웹소켓 의존성 추가
Fix: 웹 설정 파일 빠진 코드 추가
- 빠졌던 import문 다시 복구
모든 기능 로컬에서 정상 작동 확인 완료
=> Feat: 웹소켓, 알림 기능 추가

bururung/src/main/java/com/hifive/bururung/domain/credit/entity/Credit.java, bururung/src/main/java/com/hifive/bururung/domain/credit/entity/MemberCredit.java, bururung/src/main/java/com/hifive/bururung/domain/credit/entity/MemberCreditState.java, bururung/src/main/java/com/hifive/bururung/domain/credit/repository/CreditRepository.java, bururung/src/main/java/com/hifive/bururung/domain/credit/repository/MemberCreditRepository.java, bururung/src/main/java/com/hifive/bururung/domain/credit/service/IMemberCreditService.java, bururung/src/main/java/com/hifive/bururung/domain/credit/service/MemberCreditService.java, bururung/src/main/java/com/hifive/bururung/domain/member/entity/Member.java, bururung/src/main/java/com/hifive/bururung/domain/payment/controller/PaymentController.java, bururung/src/main/java/com/hifive/bururung/domain/payment/dto/ConfirmRequest.java, bururung/src/main/java/com/hifive/bururung/domain/payment/dto/PaymentConfirmResponse.java, bururung/src/main/java/com/hifive/bururung/domain/payment/dto/PaymentRequest.java, bururung/src/main/java/com/hifive/bururung/domain/payment/entity/Payment.java, bururung/src/main/java/com/hifive/bururung/domain/payment/entity/PaymentMethod.java, bururung/src/main/java/com/hifive/bururung/domain/payment/entity/PaymentState.java, bururung/src/main/java/com/hifive/bururung/domain/payment/repository/PaymentRepository.java, bururung/src/main/java/com/hifive/bururung/domain/payment/service/IPaymentService.java, bururung/src/main/java/com/hifive/bururung/domain/payment/service/PaymentService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/PaymentErrorCode.java, bururung/src/main/resources/application.yml
-[v] 기능 추가
feature/payment -> develop
크레딧, 회원크레딧, 결제 엔티티 추가
크레딧 충전 기능 추가
결제 요청, 결제 검증, 결제 승인 기능 추가
=> 크레딧, 회원크레딧, 토스페이먼츠 결제

bururung/src/main/java/com/hifive/bururung/global/common/TokenProvider.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java
-[V] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/security/jwt-role-check-> develop
- 토큰에 사용자의 권한을 담음.
-  config에서 사용자 권한에 따른 경로 설정 가능
- 차량 공유 서비스 등록 -> DRIVER 만 등록 가능
=> Feat : 권한에 따른 설정 구현

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareJoinRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/util/TaxiShareJoinAction.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/resources/mapper/taxi/TaxiShareJoinMapper.xml, bururung/src/main/resources/mapper/taxi/TaxiShareMapper.xml
-[v] 기능 추가
feat/taxi/create -> develop
- 택시 공유 알림 보내기 유틸 클래스 추가
- 상황별 알림 보내기 기능 추가
=> Feat: 택시공유 상황별 알람보내기 추가

bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/util/TaxiShareJoinAction.java
-[v] 기능 추가
feat/taxi/create
- 택시참여 알림 유틸 수정
=> Modify: 택시참여 알림 유틸 수정

bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarShareController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/dto/CarShareRegiRequestDTO.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/entity/CarShareRegistration.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarRegistrationRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/CarShareService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/ICarShareService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java
-[V] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/my-carshare-service-> develop
- config 충돌 해결 후 추가 로직 작성됨
- 프론트 연결 잘 되어야 함
- 차량 공유 서비스 등록 가능
- 내 차량 공유 서비스 전체 리스트 출력 가능
=> Feat : 차량 공유 서비스 등록 및 조회

bururung/src/main/java/com/hifive/bururung/domain/admin/controller/AdminController.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminCarRegistrationDTO.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminCarRegistrationRequest.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminCarRegistrationResponse.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminCarShareDTO.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminCarShareResponse.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminMemberDTO.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminMemberResponse.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminPaymentDTO.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminPaymentResponse.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminTaxiShareDTO.java, bururung/src/main/java/com/hifive/bururung/domain/admin/dto/AdminTaxiShareResponse.java, bururung/src/main/java/com/hifive/bururung/domain/admin/repository/IAdminMapper.java, bururung/src/main/java/com/hifive/bururung/domain/admin/service/AdminService.java, bururung/src/main/java/com/hifive/bururung/domain/admin/service/IAdminService.java, bururung/src/main/resources/mapper/admin/AdminMapper.xml, bururung/src/main/resources/mapper/statistics/StatisticsMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
feature/admin -> develop
- 회원 전체 조회 기능 추가
- 차량 등록 목록 조회 기능 추가
- 택시 공유 서비스 목록 조회 기능 추가
- 차량 공유 서비스 목록 조회 기능 추가
- 결제 목록 조회 기능 추가
- 차량 인증 수락 기능 추가
- 차량 인증 수정 요청 알림 발신 기능 추가
Fix: 회원 별점 순 조회 기능 쿼리문 수정
모든 기능 정상 작동
=> Feat: 관리자 기능 추가

bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/controller/ServiceRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/PastParticipationListResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/TodayParticipationListResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/repository/ServiceRegistrationRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/ServiceRegistrationService.java, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml, bururung/src/main/resources/mapper/carshare/participant/CreditMapper.xml
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/reservation -> develop
- 과거 차량 탑승 내역 조회 기능 추가
- 오늘 차량 탑승 내역 조회 기능 추가
- 과거 차량 탑승 내역 조회 기능 추가
- 오늘 차량 탑승 내역 조회 기능 추가
=> Feat: 과거 및 오늘 차량 공유 예약 내역 조회 기능 구현

bururung/src/main/java/com/hifive/bururung/BururungApplication.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/controller/TaxiShareJoinController.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/repository/ITaxiShareJoinRepository.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/ITaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/service/TaxiShareJoinService.java, bururung/src/main/java/com/hifive/bururung/domain/taxi/util/TaxiShareJoinAction.java, bururung/src/main/java/com/hifive/bururung/global/common/SchedulingController.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/TaxiShareJoinErrorCode.java, bururung/src/main/resources/mapper/taxi/TaxiShareJoinMapper.xml
-[] 기능 추가
feat/taxi/create - > develop
- 택시공유참여시 크레딧차감기능 구현
- 스케줄링 알람 기능 추가
=> Feat:택시공유참여시 크레딧차감기능 구현, 스케줄링 알람 기능 추가

bururung/src/main/java/com/hifive/bururung/domain/notification/controller/NotificationController.java, bururung/src/main/java/com/hifive/bururung/domain/notification/entity/Notification.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[v] 의존성, 환경 변수, 빌드 관련 코드 업데이트
chore/modify-config -> develop
chore/modify-notification-controller -> develop
설정 추가
- SecurityConfig: 필터 추가
- WebMvcConfig: 허용할 Origin 추가
주석 삭제
- NotificationController
- Notification
정상 작동
=> Chore: 설정 파일 수정 및 주석 삭제

bururung/src/main/java/com/hifive/bururung/domain/admin/controller/AdminController.java, bururung/src/main/java/com/hifive/bururung/domain/admin/repository/IAdminMapper.java, bururung/src/main/java/com/hifive/bururung/domain/admin/service/AdminService.java, bururung/src/main/java/com/hifive/bururung/domain/admin/service/IAdminService.java, bururung/src/main/resources/mapper/admin/AdminMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/admin/delete-registration -> develop
- 차량 등록 승인 취소 시 등록 삭제 기능 추가
=> Feat: 차량 등록 승인 취소 시 등록 삭제 기능 추가

bururung/build.gradle, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarShareController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/dto/MyCarServiceParticipantListResponseDTO.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarShareMapper.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/CarRegistrationService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/CarShareService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/ICarShareService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java, bururung/src/main/resources/mapper/carshare/organizer/CarShareServiceMapper.xml, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car share/mapper -> develop
- 차량 공유 서비스 등록 시 mapper 사용
=> Feat : 차량 공유 서비스 등록 mapper구현

bururung/build.gradle, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/controller/CarShareController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/dto/MyCarServiceParticipantListResponseDTO.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarShareMapper.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/repository/CarShareRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/CarRegistrationService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/CarShareService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/organizer/service/ICarShareService.java, bururung/src/main/java/com/hifive/bururung/global/common/LogAspect.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java, bururung/src/main/resources/mapper/carshare/organizer/CarShareServiceMapper.xml, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml
-[V] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[V] 의존성, 환경 변수, 빌드 관련 코드 업데이트
core/aop-log-> develop
- 현재는 차량 등록 컨트롤러 관련 메서드들만 @Before 작업 수행됨. -> 메서드명 출력
=> Core : aop 로그생성 로직 구현 (@Before)

bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[v] 의존성, 환경 변수, 빌드 관련 코드 업데이트
chore/update-link -> develop
- cors 설정에 링크 추가
=> Chore: cors 설정에 링크 추가

bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/controller/ServiceRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/AllCarListResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/entity/CarShareJoin.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/IServiceRegistrationService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml, bururung/src/main/resources/mapper/carshare/participant/CreditMapper.xml
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/reservation -> develop
- car_share_join entity 추가
- webConfig 파일 수정
- car_share_join entity 추가
- webConfig 파일 수정
=> Modify: entity 생성 및 webConfig 수정

bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/entity/CarList.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/repository/CarListRepository.java, bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java
-[] 기능 추가
-[] 기능 삭제
-[✓] 버그 수정
featrue/carshare/reservation
- WebConfig 수정
- WebConfig 수정
=> Modify: WebConfig 수정

bururung/src/main/java/com/hifive/bururung/global/config/WebMvcConfig.java, bururung/src/main/resources/application.yml
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/reservation
- yml 파일의 server 부분 수정
- yml 파일의 server 부분 수정
=> Fix: yml 파일 수정

bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/controller/ServiceRegistrationController.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/dto/PastParticipationListResponse.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/repository/ServiceRegistrationRepository.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/IServiceRegistrationService.java, bururung/src/main/java/com/hifive/bururung/domain/carshare/participant/service/ServiceRegistrationService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/resources/mapper/carshare/participant/CarshareRegistrationMapper.xml
-[✓] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/reservation
- 과거 차량 탑승 내역 조회 수정
- 과거 차량 탑승 내역 조회 시 리뷰 등록 여부 출력
=> Modify: 과거 차량 탑승 내역 조회 수정odify: 과거 차량 탑승 내역 조회 수정

bururung/src/main/java/com/hifive/bururung/domain/member/controller/MemberController.java, bururung/src/main/java/com/hifive/bururung/domain/member/entity/Member.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/IMemberService.java, bururung/src/main/java/com/hifive/bururung/domain/member/service/MemberService.java, bururung/src/main/java/com/hifive/bururung/global/config/SecurityConfig.java, bururung/src/main/java/com/hifive/bururung/global/exception/errorcode/MemberErrorCode.java
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/member -> develop
로그아웃,
access token 재발급,
회원 탈퇴 기능 추가
=> 로그아웃, 토큰 재발급, 회원탈퇴

bururung/src/main/java/com/hifive/bururung/domain/taxi/util/TaxiShareJoinAction.java, bururung/src/main/java/com/hifive/bururung/global/common/SchedulingController.java
-[] 버그 수정
feat/taxi/create-> dev
- 관리자계정 id 수정
=> Modify:관리자계정 id 수정

bururung/src/main/java/com/hifive/bururung/BururungApplication.java, bururung/src/main/java/com/hifive/bururung/global/common/JwtAuthenticationEntryPoint.java
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
develop -> main
=> Fix: ErrorPageFilter 오류 해결 시도
